spring:
      datasource:
        url: jdbc:mysql://118.25.97.210:3306/pms?useSSL=false&allowPublicKeyRetrieval=true
        username: root
        password: Hwj@12345
        driverClassName: com.mysql.cj.jdbc.Driver
mybaits:
  config-location:classpath:db/mybatis/config.xml

